# Generated by Django 4.2.16 on 2024-10-21 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='participators',
        ),
        migrations.AddField(
            model_name='exercise',
            name='participators',
            field=models.ManyToManyField(related_name='participates', to=settings.AUTH_USER_MODEL),
        ),
    ]
